### PR TITLE
64-bit build with latest rar/unrar/license

### PR DESCRIPTION
**Pull request by gingerbeardman**

### CODE REVIEW

**Comment by BlackWolf** [comment]
Wow, thanks for bringing this up-to-date after 10 years!

**Comment by gingerbeardman** [comment]
My pleasure. It was easy to do so because it is well-built! It was just settings changes with zero code changes.

Had it have been any more difficult I would have given up for sure :smile:

**Comment by gingerbeardman** [comment]
It would be great if you could add your build of the updated project to the release page.

**Comment by gingerbeardman** [comment]
@BlackWolf could you perhaps do a public release of the 64-bit version?

Meanwhile here is an unsigned 64-bit version: [RAR-Archive Utility.app.zip](https://github.com/BlackWolf/RAR-Archive-Utility/files/4803530/RAR-Archive.Utility.app.zip)

**Pull request merged**
